# Generated by Django 5.0 on 2023-12-23 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipkartapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avail',
            new_name='available',
        ),
    ]
