# Generated by Django 5.0 on 2023-12-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkartapp', '0002_rename_avail_product_available'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cat',
            new_name='category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categorys'},
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='category'),
        ),
    ]
